const mongoose = require("mongoose");

const healthProfileSchema = new mongoose.Schema(
  {
    // Link profile with user account
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      unique: true,
    },

    // Basic Information
    age: {
      type: Number,
      min: 1,
      max: 120,
    },

    gender: {
      type: String,
      enum: ["Male", "Female", "Other"],
    },

    height: {
      type: Number, // in centimeters
    },

    weight: {
      type: Number, // in kilograms
    },

    bloodGroup: {
      type: String,
      enum: [
        "A+",
        "A-",
        "B+",
        "B-",
        "AB+",
        "AB-",
        "O+",
        "O-",
      ],
    },


    // Lifestyle Information
    lifestyle: {
      activityLevel: {
        type: String,
        enum: [
          "Low",
          "Moderate",
          "High",
        ],
      },

      smoking: {
        type: Boolean,
        default: false,
      },

      alcoholConsumption: {
        type: Boolean,
        default: false,
      },

      sleepHours: {
        type: Number,
      },

      dietType: {
        type: String,
        enum: [
          "Balanced",
          "Vegetarian",
          "Vegan",
          "High Protein",
          "Other",
        ],
      },
    },


    // Medical History
    medicalHistory: {
      conditions: [
        {
          type: String,
        },
      ],

      allergies: [
        {
          type: String,
        },
      ],

      medications: [
        {
          type: String,
        },
      ],

      familyHistory: [
        {
          type: String,
        },
      ],
    },


    // Current Health Measurements
    vitals: {
      bloodPressure: {
        systolic: Number,
        diastolic: Number,
      },

      heartRate: {
        type: Number,
      },

      bloodSugar: {
        type: Number,
      },

      oxygenLevel: {
        type: Number,
      },
    },


    // ML Model Input Features
    mlFeatures: {
      type: Object,
      default: {},
    },


    // ML Prediction Results
    predictions: [
      {
        modelName: {
          type: String,
        },

        result: {
          type: Object,
        },

        confidenceScore: {
          type: Number,
        },

        predictedAt: {
          type: Date,
          default: Date.now,
        },
      },
    ],


    // Overall health score generated by analytics
    healthScore: {
      type: Number,
      min: 0,
      max: 100,
    },

  },
  {
    timestamps: true,
  }
);


module.exports = mongoose.model(
  "HealthProfile",
  healthProfileSchema
);